version: '3'
services:
  service1:
    build:
      context: ./service1
    ports:
      - "8199:8199"
    depends_on:
      - service2

  service2:
    build:
      context: ./service2
    expose:
      - "8080"
