version: '3'
services:
  service1_1:
    build:
      context: ./service1
    expose:
      - "8199"
  
  service1_2:
    build:
      context: ./service1
    expose:
      - "8199"
  
  service1_3:
    build:
      context: ./service1
    expose:
      - "8199"
  
  service2:
    build:
      context: ./service2
    expose:
      - "8080"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8198:80"  # Exposes NGINX on port 8198
    depends_on:
      - service1_1
      - service1_2
      - service1_3
      - service2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/index.html:/etc/nginx/index.html
