version: '3.8'

services:
  service1_1:
    build:
      context: ./service1
    ports:
      - "3001:3000"  # Map for debugging
      
  service1_2:
    build:
      context: ./service1
    ports:
      - "3002:3000"  # Map for debugging
      
  service1_3:
    build:
      context: ./service1
    ports:
      - "3003:3000"  # Map for debugging

  service2:
    build:
      context: ./service2
    ports:
      - "8080:8080"

  nginx:
    build:
      context: ./nginx
    ports:
      - "8198:80"  

networks:
  default:
    driver: bridge
